### ISSUE TITLE
clearfix清除浮动

### ISSUE THREAD

**Issue by Demy-ouyang** [Demy-ouyang/blog#4]
#### .clear

早期清除浮动使用比较多的是`.clear`方法，具体是在html中需要清除浮动的结构前面或者后面增加一个`div.clear`或`br.clear`。代码如下：

``` html
<div class="clear"></div>
<!--`div.clear`和`br.clear`取其一-->   
<br class="clear"/>
```

这种方法改变了html结构，相当于增加了空标签造成页面代码冗余。
#### .clearfix

clearfix清除浮动的写法很多。
- CSS写法

``` CSS
/*方法一*/
.clearfix:after{content:".";display:block;height:0;clear:both;visibility:hidden}
.clearfix{*+height:1%;}
/*方法二*/
.clearfix{overflow:auto;_height:1%}
/*方法三*/
   .clearfix{
        *zoom:1;
    }
    .clearfix:before,.clearfix:after{
        display: block;line-height:0;content:'';
    }
    .clearfix:before{
        clear:both;
    }
```
- LESS写法

``` less
.clearfix{
&:before,&:after{
    content: " ";
    display: table;
  }
  &:after{
    clear:both;
  }
}
div{
.clearfix();
}
}
```
- SASS写法

``` sass
%clearfix{
  &:before,&:after{
    content: " ";
    display: table;
  }
  &:after{
    clear:both;
  }
}
.clearfix{
@extend %clearfix;
}
div{
@extend %clearfix;
}/*需要清除浮动的div*/
```
